services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=60 #poll every 60 seconds
      - TZ=Europe/Berlin
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  builder:
    image: ghcr.io/inab/disease_perception_builder:${DISEASE_PERCEPTION_TAG:-latest}
    user: "${BUILDER_UID:-1000}:${BUILDER_GID:-1000}"
    build:
      context: ./DB
    volumes:
      - ./DB/data:/usr/src/app/data:ro
      - ./REST/DB:/usr/src/app/DB
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command: '/usr/bin/test -f /usr/src/app/DB/net_comorbidity.db -a -s /usr/src/app/DB/net_comorbidity.db || /usr/src/app/.py3env/bin/python /usr/src/app/create_db.py /usr/src/app/data /usr/src/app/DB/net_comorbidity.db'
  
  production:
    image: ghcr.io/inab/disease_perception:${DISEASE_PERCEPTION_TAG:-latest}
    build:
      context: .
    depends_on:
      builder:
        condition: service_completed_successfully
    healthcheck:
      test: /usr/bin/test -f /usr/src/app/DB/net_comorbidity.db || exit 1
      interval: 30s
      timeout: 1s
      retries: 3
    ports:
      - '${PROD_PORT:-5000}:5000'
    volumes:
      - ./REST/DB:/usr/src/app/DB:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  # This one is only used for development and local testing purposes
  nginx_production:
    image: docker.io/library/nginx:1.27
    profiles:
      - nginx
    depends_on:
      - production
    ports:
      - '8080:80'
    volumes:
      - ./conf/nginx.default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU:-1500}
